name: PunishmentGUI
version: '${project.version}'
main: se.lsbmedia.punishmentgui.Main
api-version: 1.19
authors: [ Lajjan ]
description: A GUI plugin to make punishment easier for staffs.
website: www.lsbmedia.se
commands:
  punish:
